### ISSUE TITLE
I have something wrong with ma installing Qt creator5.12.2 on CentOS 7

### ISSUE THREAD

**Issue by Tinkimi** [yafeilinux/helloworld#1]

**Comment by Tinkimi** [comment]
I've installed the Qt creator on the centos 7 ,but when I clicked the qtcreator Icon to run the program,there nathing happens ,and when I open it under the terminal,it report the error that "qt.qpa.plugin : Could not load the Qt platform plugin "xcb" in "" even though if was found.  Available platform plugins are : eglfs ,linuxfb,minimal,minimalegl,offscreen,vnc,xcb.

**Comment by Tinkimi** [comment]
@yafeilinux I wonder have you been meet this problem,and could you help me to solve this.  Thanks a lot!

**Comment by yafeilinux** [comment]
> @yafeilinux I wonder have you been meet this problem,and could you help me to solve this. Thanks a lot!
Hope this helps you:
https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found
